name: cerberus.no
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2207304
title: Everyday security solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#301D17'
    - '#774228'
    - '#FCF19B'
    - '#877777'
    - '#E86E38'
  brandStrength: 0.5247046
  lightness: 0.8168636
  saturation: 0.9242749
  rhythmicContrast: 0.75
purpose: []
