name: Cerberus
favicon: null
layout_spectrum: 0.24202
typography_spectrum: 0.2207304
title: Everyday security solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#301D17'
    - '#774228'
    - '#FCF19B'
    - '#877777'
    - '#E86E38'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
