name: Cerberus
favicon: null
layout_spectrum: 0.95558
typography_spectrum: 0.2207304
title: Everyday security solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0c'
    - '#034b9f'
    - '#f9fdfe'
    - '#7c867b'
    - '#a6b8a2'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
